name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      ecr-registry:
        description: 'The Amazon ECR registry URL'
        required: true
        type: string
        default: "783764579443.dkr.ecr.ap-south-1.amazonaws.com"
      ecr-repository:
        description: 'The Amazon ECR repository name'
        required: true
        type: string
        default: medusa
      aws-region:
        description: 'The AWS region'
        required: true
        type: string
        default: ap-south-1
      dockerfile-path:
        description: 'The path to the Dockerfile'
        required: true
        type: string
        default: ./medusa-starter-default
      

jobs:
  build:
    env:
      ECS_TASK_DEFINITION: "medusa-starter-default"
      CONTAINER_NAME: "medusa"
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Clone Medusa Server
        run: |
          git clone https://github.com/toufikj/medusa-starter-default.git

      - name: Create Dockerfile for Medusa
        run: |
          cat <<EOF > ./medusa-starter-default/Dockerfile
            # Set the base image to Node 17.1.0-alpine
            FROM node:latest

            WORKDIR /app/medusa

            COPY . .

            RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3

            RUN yarn global add @medusajs/medusa-cli

            RUN yarn

            RUN yarn build

            CMD ["sh", "-c", "npx medusa db:setup && npx medusa start"]
          EOF
      
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          tags: |
            ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}
