name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      ecr-registry:
        description: 'The Amazon ECR registry URL'
        required: true
        type: string
        default: "783764579443.dkr.ecr.ap-south-1.amazonaws.com"
      ecr-repository:
        description: 'The Amazon ECR repository name'
        required: true
        type: string
        default: medusa
      aws-region:
        description: 'The AWS region'
        required: true
        type: string
        default: ap-south-1
      dockerfile-path:
        description: 'The path to the Dockerfile'
        required: true
        type: string
        default: .
      

jobs:
  build:
    env:
      ECS_TASK_DEFINITION: "medusa-starter-default"
      CONTAINER_NAME: "medusa"
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Clone Medusa Server
        run: |
          git clone https://github.com/medusajs/medusa-starter-default.git
          git clone https://github.com/Prn-Ice/medusa-docker.git
          cd medusa-docker
          git submodule update --init --recursive --remote
          ls -l

      - name: Create Dockerfile for Medusa
        run: |
          cat <<EOF > ./Dockerfile
            # Set the base image to Node 17.1.0-alpine
            FROM node:17.1.0-alpine

            # Set the working directory
            WORKDIR /app/medusa

            # Copy the necessary files
            COPY ./medusa-starter-default/package.json .
            COPY ./medusa-docker/backend/develop.sh .
            COPY ./medusa-starter-default/yarn.* .

            # Run the apk update command to update package information
            RUN apk update

            # Install dependencies
            RUN yarn --network-timeout 1000000

            # Install the medusa-cli
            RUN yarn global add @medusajs/medusa-cli@latest

            # Add the remaining files
            COPY ./medusa-starter-default/ .

            # Set the default command to run when the container starts
            ENTRYPOINT ["sh", "develop.sh"]
          EOF
      
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          tags: |
            ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}
